package com.github.lucasaugustoss.loader.dtos;

public class AbilityEffectDTO {
    public String type;
    public String[] types;
    public String[] stats;
    public int[] stages;
    public String[] statusConditions;
    public String[] fieldConditions;
    public String[] fieldTypes;
    public String[] moves;
    public String[] categories;
    public String[] moveProperties;
    public String[] oldForms;
    public String target;
    public String chance;
    public String modifier;
    public String oldType;
    public String newType;
    public boolean trueTypes;
    public String otherAbility;
    public String statusCondition;
    public String fieldCondition;
    public String moveType;
    public String newForm;
    public String damageFraction;
    public String healFraction;
    public String pinchHP;
    public String messageType;
    public String paradoxType;
    public String trapType;
    public String modifyDamageType;
    public String statChangeCondition;
    public String specialCondition;
    public String sourceNotBlocked;
    public String sourceBlocked;
    public boolean intimidate;
    public boolean aura;
    public boolean contact;
    public double doubleValue;
    public boolean booleanValue;
    public int intValue;
    public String otherID;
    public String[] activation;
}
