package com.github.lucasaugustoss.loader.dtos;

public class MoveEffectDTO {
    public String type;
    public String effectTarget;
    public int counter;
    public String exclusiveUser;
    public boolean exclusiveForm;
    public String messageType;
    public String healFraction;
    public String[] statusConditions;
    public String[] stats;
    public int[] stages;
    public String specialCondition;
    public double modifier;
    public String chance;
    public String fieldCondition;
    public String[] fieldConditions;
    public String[] goodFieldConditions;
    public String[] badFieldConditions;
    public double accuracy;
    public String stat;
    public String target;
    public boolean semiInvulnerable;
    public String recoilType;
    public String damageFraction;
    public String counterType;
    public double maxPower;
    public String[] fieldConditionsGeneral;
    public String statusCondition;
    public String ability;
    public String moveTarget;
    public String comparedVariable;
    public double[][] amounts;
    public String move;
    public String specialHealChange;
    public String itemType;
    public boolean restorePP;
    public String fixedDamageType;
    public boolean rampage;
    public String abilityOwner;
    public String specialOHKO;
    public String[] quickChargeFieldConditions;
    public int ppAmount;
    public String changedType;
    public String otherID;
    public String[] activation;
}
